# Generated by Django 4.2.16 on 2024-09-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_date_alter_chat_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='chats', to='chat.chatuser'),
        ),
    ]
