# Generated by Django 4.2.16 on 2024-10-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='llm',
            field=models.CharField(choices=[('MistralAI', 'Mistral'), ('Ollama', 'Ollama'), ('OpenAI', 'Openai'), ('Groq', 'Groq')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=4096),
        ),
    ]
