# Generated by Django 4.2.16 on 2024-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_llm_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='prompt',
            field=models.JSONField(default=[('system', 'Início da conversa'), ('human', 'Olá, tudo bem?'), ('ai', 'Olá! Como posso ajudar?')]),
        ),
    ]
