# Generated by Django 4.2.16 on 2024-10-28 20:09

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='prompt',
            field=models.JSONField(default=chat.models.default_prompt),
        ),
    ]
