# Generated by Django 4.2.16 on 2024-10-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_main_llm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='secondary_llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_llm', to='chat.chat'),
        ),
    ]
