# Generated by Django 4.2.16 on 2024-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_is_main_llm_chat_secondary_llm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_main_llm',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='secondary_llm',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_main_llm',
            field=models.BooleanField(default=False),
        ),
    ]
