# Generated by Django 4.2.16 on 2024-11-21 17:24

import chat.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_llm_chat_main_llm_chat_secondary_llm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarpiaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(upload_to='uploads/')),
                ('llms_to_use', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MistralAI', 'Mistral'), ('Ollama', 'Ollama'), ('OpenAI', 'Openai'), ('Groq', 'Groq')], max_length=50), blank=True, default=list, size=None)),
                ('prompt', models.JSONField(default=chat.models.default_prompt)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
        ),
    ]
