# Generated by Django 4.2.16 on 2024-12-07 01:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_main_llm_alter_chat_secondary_llm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='main_llm',
            field=models.CharField(choices=[('Databricks DBRX', 'Databricks Dbrx'), ('GPT 3.5 Turbo', 'Gpt 3 5 Turbo'), ('GPT 4', 'Gpt 4'), ('GPT 4 Turbo', 'Gpt 4 Turbo'), ('GPT 4o', 'Gpt 4O'), ('GPT 4o Mini', 'Gpt 4O Mini'), ('Gemma', 'Groq Gemma'), ('Gemma 2', 'Groq Gemma 2'), ('Llama 3 8b', 'Groq Llama 3 8B'), ('Llama 3 70b', 'Groq Llama 3 70B'), ('Llama 3.1 8b', 'Groq Llama 3 1 8B'), ('Llama 3.1 70b', 'Groq Llama 3 1 70B'), ('Llama 3.2 3b', 'Groq Llama 3 2 3B'), ('Llama 3.3 70b', 'Groq Llama 3 3 70B'), ('Mixtral 8x7b', 'Groq Mixtral'), ('Mistral Nemo', 'Mistral Nemo'), ('Mistral Small', 'Mistral Small'), ('Pixtral 12b', 'Mistral Pixtral'), ('Upstage SOLAR 10.7b', 'Upstage Solar'), ('Qwen 2.5 7B Turbo', 'Qwen 2 5 7B')]),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secondary_llm',
            field=models.CharField(choices=[('Databricks DBRX', 'Databricks Dbrx'), ('GPT 3.5 Turbo', 'Gpt 3 5 Turbo'), ('GPT 4', 'Gpt 4'), ('GPT 4 Turbo', 'Gpt 4 Turbo'), ('GPT 4o', 'Gpt 4O'), ('GPT 4o Mini', 'Gpt 4O Mini'), ('Gemma', 'Groq Gemma'), ('Gemma 2', 'Groq Gemma 2'), ('Llama 3 8b', 'Groq Llama 3 8B'), ('Llama 3 70b', 'Groq Llama 3 70B'), ('Llama 3.1 8b', 'Groq Llama 3 1 8B'), ('Llama 3.1 70b', 'Groq Llama 3 1 70B'), ('Llama 3.2 3b', 'Groq Llama 3 2 3B'), ('Llama 3.3 70b', 'Groq Llama 3 3 70B'), ('Mixtral 8x7b', 'Groq Mixtral'), ('Mistral Nemo', 'Mistral Nemo'), ('Mistral Small', 'Mistral Small'), ('Pixtral 12b', 'Mistral Pixtral'), ('Upstage SOLAR 10.7b', 'Upstage Solar'), ('Qwen 2.5 7B Turbo', 'Qwen 2 5 7B')], default='Groq'),
        ),
        migrations.AlterField(
            model_name='harpialog',
            name='llms_to_use',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Databricks DBRX', 'Databricks Dbrx'), ('GPT 3.5 Turbo', 'Gpt 3 5 Turbo'), ('GPT 4', 'Gpt 4'), ('GPT 4 Turbo', 'Gpt 4 Turbo'), ('GPT 4o', 'Gpt 4O'), ('GPT 4o Mini', 'Gpt 4O Mini'), ('Gemma', 'Groq Gemma'), ('Gemma 2', 'Groq Gemma 2'), ('Llama 3 8b', 'Groq Llama 3 8B'), ('Llama 3 70b', 'Groq Llama 3 70B'), ('Llama 3.1 8b', 'Groq Llama 3 1 8B'), ('Llama 3.1 70b', 'Groq Llama 3 1 70B'), ('Llama 3.2 3b', 'Groq Llama 3 2 3B'), ('Llama 3.3 70b', 'Groq Llama 3 3 70B'), ('Mixtral 8x7b', 'Groq Mixtral'), ('Mistral Nemo', 'Mistral Nemo'), ('Mistral Small', 'Mistral Small'), ('Pixtral 12b', 'Mistral Pixtral'), ('Upstage SOLAR 10.7b', 'Upstage Solar'), ('Qwen 2.5 7B Turbo', 'Qwen 2 5 7B')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
